apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: flux-system-release-podinfo
spec:
  replicas: 3
  template:  
    spec:  
      containers:  
      - name: podinfo
        env:  
        - name: ENVIRONMENT  
          value: Production