apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: release-podinfo
  namespace: flux-system
spec:
  releaseName: podinfo
  targetNamespace: default
  interval: 1m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: ./clusters/my-cluster/podinfo/chart/
      sourceRef:
        kind: GitRepository
        name: podinfo-kube-manifest
        namespace: flux-system
      interval: 1m
      valuesFiles:
        - ./clusters/my-cluster/podinfo/chart/values.yaml
  postRenderers:
  - kustomize:
      patchesStrategicMerge:
      - kind: Deployment
        apiVersion: apps/v1
        metadata:
          name: podinfo
          labels:
            my.label.local: mylocalchart
            our.label.local: ourlocalchart
        spec:
          replicas: 2
          template:
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
                      # - key: kubernetes.io/hostname
                      #   operator: In
                      #   values:
                      #   - minikube
                      # - key: kubernetes.io/arch
                      #   operator: In
                      #   values:
                      #   - amd64
      - kind: Service
        apiVersion: v1
        metadata:
          name: podinfo
          labels:
            mysvc.label.local: mysvclocalchart
            oursvc.label.local: ourlocalchartsvc
        spec:
          type: NodePort
      - kind: Ingress
        apiVersion: networking.k8s.io/v1
        metadata:
          labels:
            mying.label.local: myinglocalchart
            oking.label.local: okinglocalchart
          name: podinfo
        spec:
          ingressClassName: null
          rules:
          - host: podinfo.ingress.local
            http:
              paths:
              - backend:
                  service:
                    name: flux-system-release-podinfo
                    port:
                      number: 9898
                path: /
                pathType: ImplementationSpecific
      - kind: Deployment
        apiVersion: apps/v1
        metadata:
          annotations:
            myredis.annottae.local: "120"
          labels:
            myredis.label.local: myredislocallabel
          name: podinfo-redis
        spec:
          replicas: 2
          revisionHistoryLimit: 5
          strategy:
            rollingUpdate:
              maxSurge: 50%
              maxUnavailable: 1
            type: RollingUpdate
      - kind: ConfigMap
        apiVersion: v1
        metadata:
          name: podinfo-redis
        data:
          redis.conf: |
            maxmemory 64mb
            maxmemory-policy allkeys-lru
            save ""
            appendonly no
            ### additional lines
            protected-mode no
            aof-use-rdb-preamble yes
  values:
    serviceAccount:
      enabled: false
    logLevel: info
    ingress:
      enabled: true
      className: ""
      annotations: {}
      hosts:
        - host: podinfo.local
          paths:
            - path: /
              pathType: ImplementationSpecific
    redis:
      enabled: true
      repository: redis
      tag: 7.0.7