apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: release-podinfo
  namespace: flux-system
spec:
  targetNamespace: flux-system
  interval: 1m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: ./clusters/my-cluster/podinfo/chart/
      sourceRef:
        kind: GitRepository
        name: podinfo-kube-manifest
        namespace: flux-system
      interval: 1m
      valuesFiles:
        - ./clusters/my-cluster/podinfo/chart/values.yaml
  postRenderers:
  - kustomize:
      patchesStrategicMerge:
      - |
        kind: Deployment
        apiVersion: apps/v1
        metadata:
          name: flux-system-release-podinfo
          labels:
            my.label.local: mylocalchart
            our.label.local: ourlocalchart
        spec:
          replicas: 1
      - |
        kind: ServiceAccount
        apiVersion: v1
        metadata:
          labels:
            mysa.label.local: mysalocalchart
            oursa.label.local: oursalocalchart
            name: flux-system-release-podinfo
  values:
    serviceAccount:
      enabled: true
    logLevel: debug