apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: release-podinfo
  namespace: flux-system
spec:
  targetNamespace: flux-system
  interval: 1m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: ./clusters/my-cluster/podinfo/chart/
      sourceRef:
        kind: GitRepository
        name: podinfo-kube-manifest
        namespace: flux-system
      interval: 1m
      valuesFiles:
        - ./clusters/my-cluster/podinfo/chart/values.yaml
  postRenderers:
  - kustomize:
      patchesStrategicMerge:
      - kind: Deployment
        apiVersion: apps/v1
        metadata:
          name: flux-system-release-podinfo
          labels:
            my.label.local: mylocalchart
            our.label.local: ourlocalchart
        spec:
          replicas: 2
      - kind: Service
        apiVersion: v1
        metadata:
          name: flux-system-release-podinfo
          labels:
            mysvc.label.local: mysvclocalchart
            oursvc.label.local: ourlocalchartsvc
        spec:
          type: NodePort
      - kind: Ingress
        apiVersion: networking.k8s.io/v1
        metadata:
          labels:
            mying.label.local: myinglocalchart
            oking.label.local: okinglocalchart
          name: flux-system-release-podinfo
        spec:
          ingressClassName: null
          rules:
          - host: podinfo.ing.local
            http:
              paths:
              - backend:
                  service:
                    name: flux-system-release-podinfo
                    port:
                      number: 9898
                path: /
                pathType: ImplementationSpecific
  values:
    serviceAccount:
      enabled: false
    logLevel: info
    ingress:
      enabled: true
      className: ""
      annotations: {}
      hosts:
        - host: podinfo.local
          paths:
            - path: /
              pathType: ImplementationSpecific
    redis:
      enabled: true
      repository: redis
      tag: 7.0.7